/* Generated by Yosys 0.62 (git sha1 7326bb7d6, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module \$paramod\debounce\CLK_FREQ=s32'00000010111110101111000010000000 (clk, rst_n, btn_raw, btn_pressed);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input btn_raw;
  wire btn_raw;
  output btn_pressed;
  wire btn_pressed;
  wire _000_;
  wire [18:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire btn_prev;
  wire btn_stable;
  wire btn_sync;
  wire [18:0] counter;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _038_ (
    .A(btn_stable),
    .SLEEP(btn_prev),
    .X(_000_)
  );
  sky130_fd_sc_hd__o31ai_1 _039_ (
    .A1(counter[5]),
    .A2(counter[7]),
    .A3(counter[6]),
    .B1(counter[8]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor4_1 _040_ (
    .A(counter[9]),
    .B(counter[11]),
    .C(counter[10]),
    .D(counter[12]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21boi_0 _041_ (
    .A1(_003_),
    .A2(_004_),
    .B1_N(counter[13]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and2_0 _042_ (
    .A(counter[15]),
    .B(counter[16]),
    .X(_006_)
  );
  sky130_fd_sc_hd__and3_1 _043_ (
    .A(counter[15]),
    .B(counter[17]),
    .C(counter[16]),
    .X(_007_)
  );
  sky130_fd_sc_hd__o211ai_1 _044_ (
    .A1(counter[14]),
    .A2(_005_),
    .B1(_007_),
    .C1(counter[18]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xor2_1 _045_ (
    .A(btn_stable),
    .B(btn_sync),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _046_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _047_ (
    .A(counter[0]),
    .B(_010_),
    .Y(_001_[0])
  );
  sky130_fd_sc_hd__xnor2_1 _048_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _049_ (
    .A(_010_),
    .B(_011_),
    .Y(_001_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _050_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1(counter[2]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__and3_1 _051_ (
    .A(counter[2]),
    .B(counter[0]),
    .C(counter[1]),
    .X(_013_)
  );
  sky130_fd_sc_hd__nor3_1 _052_ (
    .A(_010_),
    .B(_012_),
    .C(_013_),
    .Y(_001_[2])
  );
  sky130_fd_sc_hd__nor2_1 _053_ (
    .A(counter[3]),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and4_1 _054_ (
    .A(counter[3]),
    .B(counter[2]),
    .C(counter[0]),
    .D(counter[1]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor3_1 _055_ (
    .A(_010_),
    .B(_014_),
    .C(_015_),
    .Y(_001_[3])
  );
  sky130_fd_sc_hd__nor2_1 _056_ (
    .A(counter[4]),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__and2_0 _057_ (
    .A(counter[4]),
    .B(_015_),
    .X(_017_)
  );
  sky130_fd_sc_hd__nor3_1 _058_ (
    .A(_010_),
    .B(_016_),
    .C(_017_),
    .Y(_001_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _059_ (
    .A(counter[5]),
    .B(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _060_ (
    .A(_010_),
    .B(_018_),
    .Y(_001_[5])
  );
  sky130_fd_sc_hd__a21oi_1 _061_ (
    .A1(counter[5]),
    .A2(_017_),
    .B1(counter[6]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__and4_1 _062_ (
    .A(counter[4]),
    .B(counter[5]),
    .C(counter[6]),
    .D(_015_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor3_1 _063_ (
    .A(_010_),
    .B(_019_),
    .C(_020_),
    .Y(_001_[6])
  );
  sky130_fd_sc_hd__and2_0 _064_ (
    .A(counter[7]),
    .B(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _065_ (
    .A(_010_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o21a_1 _066_ (
    .A1(counter[7]),
    .A2(_020_),
    .B1(_022_),
    .X(_001_[7])
  );
  sky130_fd_sc_hd__nor2_1 _067_ (
    .A(counter[8]),
    .B(_021_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a211oi_1 _068_ (
    .A1(counter[8]),
    .A2(_021_),
    .B1(_023_),
    .C1(_010_),
    .Y(_001_[8])
  );
  sky130_fd_sc_hd__a21oi_1 _069_ (
    .A1(counter[8]),
    .A2(_021_),
    .B1(counter[9]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__and4_1 _070_ (
    .A(counter[7]),
    .B(counter[9]),
    .C(counter[8]),
    .D(_020_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _071_ (
    .A(_010_),
    .B(_024_),
    .C(_025_),
    .Y(_001_[9])
  );
  sky130_fd_sc_hd__and2_0 _072_ (
    .A(counter[10]),
    .B(_025_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _073_ (
    .A(counter[10]),
    .B(_025_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor3_1 _074_ (
    .A(_010_),
    .B(_026_),
    .C(_027_),
    .Y(_001_[10])
  );
  sky130_fd_sc_hd__a21oi_1 _075_ (
    .A1(counter[11]),
    .A2(_026_),
    .B1(_010_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o21a_1 _076_ (
    .A1(counter[11]),
    .A2(_026_),
    .B1(_028_),
    .X(_001_[11])
  );
  sky130_fd_sc_hd__and4_1 _077_ (
    .A(counter[11]),
    .B(counter[10]),
    .C(counter[12]),
    .D(_025_),
    .X(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _078_ (
    .A1(counter[11]),
    .A2(_026_),
    .B1(counter[12]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor3_1 _079_ (
    .A(_010_),
    .B(_029_),
    .C(_030_),
    .Y(_001_[12])
  );
  sky130_fd_sc_hd__a21oi_1 _080_ (
    .A1(counter[13]),
    .A2(_029_),
    .B1(_010_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o21a_1 _081_ (
    .A1(counter[13]),
    .A2(_029_),
    .B1(_031_),
    .X(_001_[13])
  );
  sky130_fd_sc_hd__and3_1 _082_ (
    .A(counter[13]),
    .B(counter[14]),
    .C(_029_),
    .X(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _083_ (
    .A1(counter[13]),
    .A2(_029_),
    .B1(counter[14]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _084_ (
    .A(_010_),
    .B(_032_),
    .C(_033_),
    .Y(_001_[14])
  );
  sky130_fd_sc_hd__a41oi_1 _085_ (
    .A1(counter[13]),
    .A2(counter[14]),
    .A3(counter[15]),
    .A4(_029_),
    .B1(_010_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o21a_1 _086_ (
    .A1(counter[15]),
    .A2(_032_),
    .B1(_034_),
    .X(_001_[15])
  );
  sky130_fd_sc_hd__a41oi_1 _087_ (
    .A1(counter[13]),
    .A2(counter[14]),
    .A3(counter[15]),
    .A4(_029_),
    .B1(counter[16]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a211oi_1 _088_ (
    .A1(_006_),
    .A2(_032_),
    .B1(_035_),
    .C1(_010_),
    .Y(_001_[16])
  );
  sky130_fd_sc_hd__a41oi_1 _089_ (
    .A1(counter[13]),
    .A2(counter[14]),
    .A3(_006_),
    .A4(_029_),
    .B1(counter[17]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a211oi_1 _090_ (
    .A1(_007_),
    .A2(_032_),
    .B1(_036_),
    .C1(_010_),
    .Y(_001_[17])
  );
  sky130_fd_sc_hd__a41oi_1 _091_ (
    .A1(counter[13]),
    .A2(counter[14]),
    .A3(_007_),
    .A4(_029_),
    .B1(counter[18]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _092_ (
    .A(_010_),
    .B(_037_),
    .Y(_001_[18])
  );
  sky130_fd_sc_hd__mux2_1 _093_ (
    .A0(btn_sync),
    .A1(btn_stable),
    .S(_008_),
    .X(_002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _094_ (
    .CLK(clk),
    .D(_000_),
    .Q(btn_pressed),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _095_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(counter[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _096_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(counter[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _097_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(counter[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(counter[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(counter[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(counter[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(counter[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(counter[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(counter[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(counter[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(clk),
    .D(_001_[10]),
    .Q(counter[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _106_ (
    .CLK(clk),
    .D(_001_[11]),
    .Q(counter[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(clk),
    .D(_001_[12]),
    .Q(counter[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _108_ (
    .CLK(clk),
    .D(_001_[13]),
    .Q(counter[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _109_ (
    .CLK(clk),
    .D(_001_[14]),
    .Q(counter[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _110_ (
    .CLK(clk),
    .D(_001_[15]),
    .Q(counter[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _111_ (
    .CLK(clk),
    .D(_001_[16]),
    .Q(counter[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _112_ (
    .CLK(clk),
    .D(_001_[17]),
    .Q(counter[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _113_ (
    .CLK(clk),
    .D(_001_[18]),
    .Q(counter[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _114_ (
    .CLK(clk),
    .D(btn_raw),
    .Q(btn_sync),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _115_ (
    .CLK(clk),
    .D(btn_stable),
    .Q(btn_prev),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _116_ (
    .CLK(clk),
    .D(_002_),
    .Q(btn_stable),
    .RESET_B(rst_n)
  );
endmodule

module digital_password_lock(clk, rst_n, btn, pw_switch, green_led, red_led, state_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input btn;
  wire btn;
  input [3:0] pw_switch;
  wire [3:0] pw_switch;
  output green_led;
  wire green_led;
  output red_led;
  wire red_led;
  output [2:0] state_out;
  wire [2:0] state_out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire [23:0] _32_;
  wire [23:0] _33_;
  wire blink;
  wire [23:0] blink_counter;
  wire btn_pressed;
  wire [3:0] entered_pw;
  wire [1:0] fail_count;
  wire match;
  wire [2:0] state;
  sky130_fd_sc_hd__clkinv_1 _34_ (
    .A(blink_counter[0]),
    .Y(_32_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _35_ (
    .A(state[0]),
    .SLEEP(blink),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor3b_1 _36_ (
    .A(state[1]),
    .B(_05_),
    .C_N(state[2]),
    .Y(red_led)
  );
  sky130_fd_sc_hd__nand2_1 _37_ (
    .A(blink_counter[0]),
    .B(blink_counter[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xor2_1 _38_ (
    .A(blink_counter[0]),
    .B(blink_counter[1]),
    .X(_33_[1])
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(blink_counter[2]),
    .B(_06_),
    .Y(_33_[2])
  );
  sky130_fd_sc_hd__and4_1 _40_ (
    .A(blink_counter[0]),
    .B(blink_counter[1]),
    .C(blink_counter[2]),
    .D(blink_counter[3]),
    .X(_07_)
  );
  sky130_fd_sc_hd__a31oi_1 _41_ (
    .A1(blink_counter[0]),
    .A2(blink_counter[1]),
    .A3(blink_counter[2]),
    .B1(blink_counter[3]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_07_),
    .B(_08_),
    .Y(_33_[3])
  );
  sky130_fd_sc_hd__nand2_1 _43_ (
    .A(blink_counter[4]),
    .B(_07_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xor2_1 _44_ (
    .A(blink_counter[4]),
    .B(_07_),
    .X(_33_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(blink_counter[5]),
    .B(_09_),
    .Y(_33_[5])
  );
  sky130_fd_sc_hd__and4_1 _46_ (
    .A(blink_counter[4]),
    .B(blink_counter[5]),
    .C(blink_counter[6]),
    .D(_07_),
    .X(_10_)
  );
  sky130_fd_sc_hd__a31oi_1 _47_ (
    .A1(blink_counter[4]),
    .A2(blink_counter[5]),
    .A3(_07_),
    .B1(blink_counter[6]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _48_ (
    .A(_10_),
    .B(_11_),
    .Y(_33_[6])
  );
  sky130_fd_sc_hd__nand2_1 _49_ (
    .A(blink_counter[7]),
    .B(_10_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xor2_1 _50_ (
    .A(blink_counter[7]),
    .B(_10_),
    .X(_33_[7])
  );
  sky130_fd_sc_hd__xnor2_1 _51_ (
    .A(blink_counter[8]),
    .B(_12_),
    .Y(_33_[8])
  );
  sky130_fd_sc_hd__nand4_1 _52_ (
    .A(blink_counter[7]),
    .B(blink_counter[8]),
    .C(blink_counter[9]),
    .D(_10_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a31oi_1 _53_ (
    .A1(blink_counter[7]),
    .A2(blink_counter[8]),
    .A3(_10_),
    .B1(blink_counter[9]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _54_ (
    .A(_13_),
    .SLEEP(_14_),
    .X(_33_[9])
  );
  sky130_fd_sc_hd__xnor2_1 _55_ (
    .A(blink_counter[10]),
    .B(_13_),
    .Y(_33_[10])
  );
  sky130_fd_sc_hd__and3b_1 _56_ (
    .A_N(state[2]),
    .B(state[1]),
    .C(state[0]),
    .X(green_led)
  );
  sky130_fd_sc_hd__clkinv_1 _57_ (
    .A(green_led),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor3b_1 _58_ (
    .A(state[2]),
    .B(state[0]),
    .C_N(state[1]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor4b_1 _59_ (
    .A(state[2]),
    .B(state[0]),
    .C(match),
    .D_N(state[1]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor2_1 _60_ (
    .A(fail_count[0]),
    .B(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand2_1 _61_ (
    .A(fail_count[0]),
    .B(_17_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor3b_1 _62_ (
    .A(green_led),
    .B(_18_),
    .C_N(_19_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _63_ (
    .A(fail_count[1]),
    .B(_19_),
    .X(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _64_ (
    .A(green_led),
    .B(_20_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _65_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor2_1 _66_ (
    .A(green_led),
    .B(_21_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _67_ (
    .A(btn_pressed),
    .B(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _68_ (
    .A(fail_count[1]),
    .SLEEP(fail_count[0]),
    .X(_24_)
  );
  sky130_fd_sc_hd__o21ai_0 _69_ (
    .A1(match),
    .A2(_24_),
    .B1(_16_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nand3b_1 _70_ (
    .A_N(state[1]),
    .B(state[0]),
    .C(state[2]),
    .Y(_26_)
  );
  sky130_fd_sc_hd__and3_1 _71_ (
    .A(_22_),
    .B(_25_),
    .C(_26_),
    .X(_27_)
  );
  sky130_fd_sc_hd__o22ai_1 _72_ (
    .A1(btn_pressed),
    .A2(_15_),
    .B1(_23_),
    .B2(_27_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _73_ (
    .A(match),
    .B(_16_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nand2_1 _74_ (
    .A(state[1]),
    .B(btn_pressed),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nand2_1 _75_ (
    .A(state[0]),
    .B(_29_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__o21ai_0 _76_ (
    .A1(state[2]),
    .A2(_30_),
    .B1(_28_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2b_1 _77_ (
    .A_N(_17_),
    .B(_26_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a21o_1 _78_ (
    .A1(state[2]),
    .A2(_23_),
    .B1(_31_),
    .X(_04_)
  );
  sky130_fd_sc_hd__dfrtp_1 _79_ (
    .CLK(clk),
    .D(_00_),
    .Q(fail_count[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _80_ (
    .CLK(clk),
    .D(_01_),
    .Q(fail_count[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _81_ (
    .CLK(clk),
    .D(_02_),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _82_ (
    .CLK(clk),
    .D(_03_),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _83_ (
    .CLK(clk),
    .D(_04_),
    .Q(state[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _84_ (
    .CLK(clk),
    .D(_32_[0]),
    .Q(blink_counter[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _85_ (
    .CLK(clk),
    .D(_33_[1]),
    .Q(blink_counter[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _86_ (
    .CLK(clk),
    .D(_33_[2]),
    .Q(blink_counter[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _87_ (
    .CLK(clk),
    .D(_33_[3]),
    .Q(blink_counter[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _88_ (
    .CLK(clk),
    .D(_33_[4]),
    .Q(blink_counter[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _89_ (
    .CLK(clk),
    .D(_33_[5]),
    .Q(blink_counter[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _90_ (
    .CLK(clk),
    .D(_33_[6]),
    .Q(blink_counter[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _91_ (
    .CLK(clk),
    .D(_33_[7]),
    .Q(blink_counter[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _92_ (
    .CLK(clk),
    .D(_33_[8]),
    .Q(blink_counter[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _93_ (
    .CLK(clk),
    .D(_33_[9]),
    .Q(blink_counter[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _94_ (
    .CLK(clk),
    .D(_33_[10]),
    .Q(blink_counter[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _95_ (
    .CLK(clk),
    .D(blink_counter[10]),
    .Q(blink),
    .RESET_B(rst_n)
  );
  password_core core (
    .entered_pw(entered_pw),
    .match(match)
  );
  \$paramod\debounce\CLK_FREQ=s32'00000010111110101111000010000000  debounce_inst (
    .btn_pressed(btn_pressed),
    .btn_raw(btn),
    .clk(clk),
    .rst_n(rst_n)
  );
  register4 pw_register (
    .clk(clk),
    .d(pw_switch),
    .load(btn_pressed),
    .q(entered_pw),
    .rst_n(rst_n)
  );
  assign _32_[23:1] = blink_counter[23:1];
  assign _33_[0] = _32_[0];
  assign state_out = state;
endmodule

module password_core(entered_pw, match);
  input [3:0] entered_pw;
  wire [3:0] entered_pw;
  output match;
  wire match;
  sky130_fd_sc_hd__and4b_1 _0_ (
    .A_N(entered_pw[2]),
    .B(entered_pw[3]),
    .C(entered_pw[0]),
    .D(entered_pw[1]),
    .X(match)
  );
endmodule

module register4(clk, rst_n, load, d, q);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input load;
  wire load;
  input [3:0] d;
  wire [3:0] d;
  output [3:0] q;
  wire [3:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  sky130_fd_sc_hd__mux2_1 _04_ (
    .A0(q[0]),
    .A1(d[0]),
    .S(load),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _05_ (
    .A0(q[1]),
    .A1(d[1]),
    .S(load),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _06_ (
    .A0(q[2]),
    .A1(d[2]),
    .S(load),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _07_ (
    .A0(q[3]),
    .A1(d[3]),
    .S(load),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _08_ (
    .CLK(clk),
    .D(_00_),
    .Q(q[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _09_ (
    .CLK(clk),
    .D(_01_),
    .Q(q[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_02_),
    .Q(q[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(_03_),
    .Q(q[3]),
    .RESET_B(rst_n)
  );
endmodule
